### ISSUE TITLE
The __lt__, __gt__, and __eq__ operators implement incorrect comparisons.

### ISSUE THREAD

**Issue by jsharkey13** [CopOnTheRun/FB-Message-Parser#2]
In the fb_chat file in the Message class, the Python comparison operators compare the wrong thing:
They currently use the sent_before() function, which takes a date as an argument. However, the __lt__ operator receives a Message object as an argument.

``` python
    def __lt__(self, date):
        return self.sent_before(date)

    def sent_before(self,date):
        return self.date_time < date
```

To perform the correct comparison, the Message.date_time should be passed to sent_before()

``` python
def __lt__(self, message):
        return self.sent_before(message.date_time)
```

and similarly for the __gt__ method.

**Comment by CopOnTheRun** [comment]
This is a good point, comparison operators should compare objects of the same type.
